### ISSUE TITLE
Main Logo Redesign

### ISSUE THREAD

**Issue by RexYuan** [communityNTNU/assemblyNTNU#1]
I don't like it.

**Comment by RexYuan** [comment]
So ummm... I think we'll need to find someone else to do it.
I'll be actively looking for help.

**Comment by RexYuan** [comment]
@wi1d5ky I'm sorry... I tried

![logo1](https://cloud.githubusercontent.com/assets/5001650/10268795/6d211064-6af6-11e5-91e4-71c1d5c91db0.png)
![logo2](https://cloud.githubusercontent.com/assets/5001650/10268796/6ef57736-6af6-11e5-8f18-09711ebef920.png)
![logo3](https://cloud.githubusercontent.com/assets/5001650/10268797/703fa454-6af6-11e5-8d19-75333565dbd9.png)
![logo4](https://cloud.githubusercontent.com/assets/5001650/10268799/7295f9b0-6af6-11e5-9f41-b8c84e73a4db.png)

**Comment by RexYuan** [comment]
不過... 個人滿喜歡第二個的

**Comment by RexYuan** [comment]
@wi1d5ky 如果你覺得還看得順眼 就直接選個吧！

**Comment by wildskyf** [comment]
我覺得都蠻不錯的XD 比較喜歡前兩個。
第三個感覺很像半成品，應該可以再加一些幾何圖形之類的；
第四個就是那樣（？），但我喜歡中文。

**Comment by wildskyf** [comment]
現在這個 org 的 icon 看來也是挺不錯

**Comment by RexYuan** [comment]
那就先暫定第四個囉 字體是 [Natural Writing Brush(HOT-Ninja Std R) Font-Traditional Chinese](https://chinesefontdesign.com/natural-writing-brushhot-ninja-std-r-font-traditional-chinese.html)

這是[原檔案](https://www.dropbox.com/s/gx2fjfyx7lqclye/logo4.png?dl=0)（我是直接用最簡單的方法 Mac 的 Preview 做的 需要可以直接改或重製）

**Comment by wildskyf** [comment]
使用這個字體作為 logo 就授權上來說沒有問題吧？

Chih-cheng Yuan notifications@github.com 於 2015年10月7日 週三 下午12:34寫道：

**Comment by RexYuan** [comment]
這個嘛⋯⋯ 不知道欸
也不知道該問誰 我先在那個網站留言了

**Comment by RexYuan** [comment]
ummmm 他回應說沒有business license 但是我再查了一下後發現這個好像事實上叫做白舟忍者 也不確定到底他是不是版權所有人
