### ISSUE TITLE
施大

### ISSUE THREAD

**Issue by RexYuan** [communityNTNU/assemblyNTNU#3]
圖書館現在工人直接在我旁邊拆屋頂
應該搞個專門婊這個施工的東西

**Comment by wildskyf** [comment]
詳細希望

**Comment by RexYuan** [comment]
:(

**Comment by RexYuan** [comment]
發現不能直接用郵件附件圖片...
http://i.imgur.com/CdG7BAS.jpg

**Comment by RexYuan** [comment]
這應該會是issue board原型的好開始 我會去問問有沒有哪個工程可以開始追蹤

**Comment by RexYuan** [comment]
想一下後覺得算了⋯⋯ 只是剛好今天很北宋 之後等到issueboard一起做 這個頂多有做longform等的潛力但曠日費時

**Comment by wildskyf** [comment]
同意，我也可以體會有時候很美送的時候會想上來報 bug 的心情XD

**Comment by wildskyf** [comment]
BTW, 郵件你可能要打成 `[圖片替代文字](圖片網址)`
也就是利用 Markdown 支援的 img 語法來附圖。
