### ISSUE TITLE
網域要用什麼

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/assemblyNTNU#5]
剛看了一下 ntnu.org.tw 可以註冊
但我覺得有點長
而 ntnu.org ntnu.tw 都不能用Orz

**Comment by wildskyf** [comment]
是也可以叫做 ntnu.com，com stand for COMmunity
但要到這裡來買… 
https://sedo.com/search/details.php4?partnerid=24550&language=cn&domain=ntnu.com

**Comment by wildskyf** [comment]
目前的網址使用 ntnu.com.tw
未來的目標是 ntnu.tw

**Comment by RexYuan** [comment]
course 也準備換了

![screen shot 2015-12-16 at 3 31 38 pm](https://cloud.githubusercontent.com/assets/5001650/11834799/98e62c82-a40a-11e5-83c8-187c4aa6a34c.png)

**Comment by wildskyf** [comment]
course 你有空給我需要的資料，諸如要設 CNAME 還是 A 或是 AA，你再跟我說～
