### ISSUE TITLE
Work flow

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/assemblyNTNU#6]
@RexYuan 
我覺得要討論一下 work flow，應該要加個 Code Review 的流程。
避免有什麼更改的人沒注意到的情況。

**Comment by RexYuan** [comment]
我也有同感 不過不知道有什麼辦法 :confused:

**Comment by wildskyf** [comment]
最後還是覺得要 review 一下，所以 @RexYuan ，可能要請你開一個  reviewer 的 team（擁有比較高的權限），然後一般的 Team 就沒有 repo 權限。
步驟：
1. Pull upstream gh-pages
2. 開新 Branch
3. Modify Something
4. Commit, then go to 5 or 3
5. Push origin
6. Pull request
7. Review
8. This code is ok? Merge : Back to 3

簡單的流程大概是這樣。

**Comment by wildskyf** [comment]
@RexYuan ，你覺得 ok 的話就直接把我上面寫的放到這個 repo 的 README 中，然後 close 掉這個 issue。

**Comment by RexYuan** [comment]
我覺得很 ok！

**Comment by wildskyf** [comment]
ref: http://www.codingstyle.cn/topics/35
